### ISSUE TITLE
Display Typified Name in AVH

### ISSUE THREAD

**Issue by acvaughan** [AtlasOfLivingAustralia/avh-hub#24]
We would like to see Typified name indexed so it can be faceted and so people can search on it and download it.

This will be necessary in order to correctly display type information in the collections browser once type images are delivered by herbaria (first batch is due in late March 2015).

**Comment by nielsklazenga** [comment]
I second that. We first need to fix the typifiedName element though. At the moment what is displayed as Typified name is previousIdentifications. This is probably because the data was initially migrated from AVH 3 and the typified name is now delivered with a rather opaque ABCD URI (http://wiki.tdwg.org/twiki/bin/view/ABCD/AbcdConcept0604). I suggest deleting the field from AVH and then I can redeliver it with a proper HISPID URI (http://hiscom.chah.org.au/hispid/terms/typifiedName).

**Comment by nickdos** [comment]
We could try to index `Abcd type status` against thee SOLR `type_status ` field...

**Comment by nielsklazenga** [comment]
That would work for the type status facet, so that's part of a solution, but in addition to the "type status" we would also like TypifiedName indexed. There is a data management issue with TypifiedName, as what is currently in the TypifiedName field in the database is in fact previousIdentifications.

**Comment by m-hope** [comment]
This is mainly a data issue... DwC doesn't have a TypifiedName field...  this will become more relevant when Herbaria start delivering GPI images.

**Comment by m-hope** [comment]
This issue was again discussed at HISCOM (2017), so have removed the low priority... Need to understand it more re: how it is delivered and where it is used...

**Comment by nielsklazenga** [comment]
Just FYI, there will be a `typifiedName` property in the next set of changes to Darwin Core (https://github.com/tdwg/dwc/issues/28).
