### ISSUE TITLE
records not displaying on mapview

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/avh-hub#40]
A user has reported that when she searches for some species in specific IBRA areas, the records don't display on the map view even though the search returns records that have coordinate info.  This only occurs for some taxa.  An example where the records don't display is:

http://avh.ala.org.au/occurrences/search?q=cl1048%3A%22Eyre+Yorke+Block%22+matched_name_children%3AWurmbea#tab_mapView

Interestingly, if you rearrange the search terms as follows the records display fine, eg: 

http://avh.ala.org.au/occurrences/search?q=wurmbea&fq=cl1048%3A%22Eyre+Yorke+Block%22#tab_mapView

The problem also occurs on the main ALA site as well...

**Comment by ben3000** [comment]
The following entries appear in the second query, but not in the first:

- http://avh.ala.org.au/occurrences/2c0e6bd0-2c6c-4ffc-8b7d-8099e3f7e983
- http://avh.ala.org.au/occurrences/8aa87c63-7e1d-4ac2-b189-62fb1f207093

**Comment by nielsklazenga** [comment]
Those two entries are for names (Wurmbea sp. and Wurmbea aff. something) that are matched to 'Liliaceae', so if you do a matched name query (first query) you are not going to find them, but if you do a text search (second query), you do. The second query is not a simple rearrangement of search terms, it is a different query with different search terms. 

The 'matched_name_children' term has caused nothing but trouble since it was introduced a few months ago.

**Comment by ben3000** [comment]
I just had a similar problem with a taxon name query vs a plain text query for "banksia attenuata", which in the taxon name query is split into two, namely "Banksia attenuata" and "Banksia attenuata R.Br." names. This is confusing and, I think, unwarranted.

**Comment by m-hope** [comment]
The original of records not displaying on the map appears to be resolved with the release of the Australasian Virtual Herbarium.
The second issue around 'matched_name_children' is being addressed in issue #69
