### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/avh-hub#64]
The Map is not showing on the latest snapshot version (not deployed yet), although the new Download button is showing and is functional:

<img width="1255" alt="screen shot 2016-10-27 at 11 40 30 am" src="https://cloud.githubusercontent.com/assets/82365/19750120/537aa604-9c3a-11e6-87da-5a6625c94c75.png">

This is compared to issues on apa-hub where both the new Download button and the Map is not showing, https://github.com/AtlasOfLivingAustralia/apa-hub/issues/6 https://github.com/AtlasOfLivingAustralia/apa-hub/issues/7

**Comment by nickdos** [comment]
This is due to Google grand-fathering old domains for the API key check. avh.ala.org.au is grandfathered, as is dev.ala.org.au but localhost is not.  So fix is to have an entry in /etc/hosts for dev.ala.org.au pointing to localhost. There is a config property we can change to use the new Google API key method, which Dave added for international users...
