### ISSUE TITLE
Simplify searching for provided vs matched names

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/avh-hub#73]
In AVH advanced search, the taxon search options should provide a toggle to search for provided, matched (or even both)...
![search_for_records___the_australasian_virtual_herbarium](https://user-images.githubusercontent.com/532845/31369825-bcf96ee4-add2-11e7-83b4-3c12958d7d8f.png)

Discuss with Niels and Frank to get user stories for this issue.

**Comment by m-hope** [comment]
This was discussed at the HISCOM meeting in Melbourne (Oct 2017).  Comments as follows:
 - All agreed this would meet requirements,
 - The "matched name" option should be the default setting
 - This toggle needs to be on each line of Taxon name search (ie: allows users to search for matched and provided name for a particular taxon).
 - Need this toggle option to be available for the Batch Taxonomic search as well.

**Comment by nickdos** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-store/issues/322 is a blocker for the batch taxon search form implementing the same feature.

**Comment by nickdos** [comment]
Try it out on the test server https://avh-test.ala.org.au/search#tab_advanceSearch
@nielsklazenga

**Comment by nielsklazenga** [comment]
Thanks @nickdos ,
The search on provided name doesn't work. I think this might be because it prepends the first item with 'AND':

https://avh-test.ala.org.au/occurrences/search?q=%28raw_name%3A+AND+%22Dicranoloma+dicarpum%22+OR+raw_name%3A%22Dicranoloma+robustum%22%29

Also, the auto-completion doesn't work, but I expect that is because we are in a different domain?

As to the reference to AtlasOfLivingAustralia/biocache-store#322 as a blocker for the batch taxon search on matched name, I think case-sensitive search is completely fine (as long as we make people aware). I know from my experience with SOLR what a pain it is to combine case-insensitive search with a wild card.

**Comment by nickdos** [comment]
I fixed the `AND` bug but it didn't get included in the build - will trigger another build.

I'll look at autocomplete too.

**Comment by nielsklazenga** [comment]
Thanks @nickdos . Time to go home...

**Comment by nielsklazenga** [comment]
@nickdos, the supplied name search now works, but the matched name search gives an internal server error.

Also, would it be possible to have both radio boxes on the same line with 'Matched name' and 'Supplied name' as labels, and the whole strings you've got now (or just the bits in parentheses) as title attributes? I think that would work well.

**Comment by nickdos** [comment]
@nielsklazenga I'm not seeing the internal server error, can you tell me the names you were using to get the error? 

I'm not sure having the radio boxes on the same line is a good idea - vertical is generally accepted way to display radio buttons. Here what one UX site says:

> Try To Lay Out Your Lists Vertically
Horizontal radio buttons are sometimes difficult to scan and to localize. The horizontal arrangement of the radio buttons can also make it challenging to tell with which label the radio button corresponds: the one before the button or the one after. Vertical positioning of radio buttons is safer.

Seeing as there is additional "explanation" text with the options, having it all in one line would be confusing IMO. 

Probably clearer would be 3 lines, like:
> Search against the:
[•] "matched" name (accepted name) - results will include synonyms
[_] "supplied" name (verbatim name) - results will not include synonyms

**Comment by nielsklazenga** [comment]
@nickdos because this is a toggle and not really a search field, I think the better separation between the toggle and the search fields that putting everything on one line provides outweighs the other UX argument, but this is not the most important.

I am okay with having the radios on separate lines, but I would like the labels to be just 'Matched name' and 'Supplied name'. We are in a search form, so the 'Search against the:' bit is repetitive and superfluous, the quotes/inverted commas should go, as they suggest that you are really searching for something else than what the words indicate and the '(accepted name}' and '(verbatim name)' are not exactly accurate – the supplied name is most likely the accepted name at the herbarium that supplied the record – and will cause more confusion than they resolve. The explanation is nice, but I had hoped that could go in a `title` attribute, as none of the other elements have it.

Like this:

```html
<div class="radio">
  <label title="Matched name – results will include known synonyms">
    <input type="radio" name="nameType" id="nameType_1" value="taxa" checked>
    Matched name
  </label>
</div>
<div class="radio">
  <label title="Supplied name – results will not include synonyms">
    <input type="radio" name="nameType" id="nameType_2" value="raw_name">
    Supplied name
  </label>
</div>
```
@acvaughan, do you have an opinion on this?

By the way @nickdos , this is not criticism, just pedantry.

**Comment by nickdos** [comment]
I'm OK with that... we could add a tooltip instead of just `title`. Any suggestions for the detailed version in title/tooltip?

A bit like (but onMouseOver instead of onClick)
![image](https://user-images.githubusercontent.com/532845/52456381-9e30a900-2ba8-11e9-93d6-1607e1ea716f.png)

Also the error you got with the matched name - can you send me the queries you used to trigger that please?

**Comment by nielsklazenga** [comment]
Awesome, I will have a think about the tooltip text.

There is no more server error on the matched name search.

**Comment by nickdos** [comment]
New version is up for testing https://avh-test.ala.org.au/search#tab_advanceSearch

**Comment by nielsklazenga** [comment]
Thanks @nickdos. I had conveniently forgotten about the text for the popups. What you've got there now is fine.

Works well too. Interestingly the Matched name search, including synonyms (https://avh-test.ala.org.au/occurrences/search?taxa=Dicranoloma+robustum+OR+Dicranoloma+menziesii&q=) gives fewer records than the supplied name search (https://avh-test.ala.org.au/occurrences/search?q=%28raw_name%3A%22Dicranoloma+robustum%22+OR+raw_name%3A%22Dicranoloma+menziesii%22%29). I wonder how that is possible. Will have to compare some downloads when this is in production.

**Comment by nickdos** [comment]
Yes, I asked the same question of the data team... my initial guess is there are achhort of records which have not been matched to an accepted names (where the name is legit and valid) due to some processing error. A re-index should fix this. I'll raise a separate issue (I asked in Slack only - just pinged you on the thread now @nielsklazenga).

**Comment by adam-collins** [comment]
Appears resolved.
