### ISSUE TITLE
Sorting by Record date in search results

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#78]
Sorting search results by Record date gives very confusing results. It appears that records with an incomplete or no event date have been given a Record date of 0, so, when sorting on it, records with an incomplete or missing even date end up between the records from before 1 Jan. 1970 and those from after 1 Jan. 1970, instead of at the end or beginning.

See, for example, http://avh.ala.org.au/occurrences/search?fq=&pageSize=400&sort=occurrence_date&taxa=Cenchrus%20purpurascens.

**Comment by adam-collins** [comment]
Still an issue.

**Comment by adam-collins** [comment]
This can be achieved by adding `sortMissingLast="true"` to the SOLR schema `<fieldType name="date" class="solr.DatePointField" omitNorms="true">`. 

It will result in all date field searches putting the null values at the end. 
- Sorting `eventDate desc` puts nulls at the end
- Sorting `eventDate asc` puts nulls at the end

Since we discourage deep paging this should not be an issue. Need other opinions and to see what it does to charts and facet sorting.

**Comment by adam-collins** [comment]
Facets are unchanged.

Charting is unchanged because ranges are used when not based on facets.

**Comment by adam-collins** [comment]
See commit https://github.com/gbif/pipelines/commit/72767b10846d476b8ca9d6b92352924b9bb7675e. It might be a long time before this makes it into production.

**Comment by nielsklazenga** [comment]
Thanks for looking into this @adam-collins.

**Comment by adam-collins** [comment]
pull request https://github.com/gbif/pipelines/pull/1035

**Comment by nickdos** [comment]
Hi @nielsklazenga - can you pls check if this issue has been fixed and close it if it looks OK?

**Comment by nielsklazenga** [comment]
Yup, looks good for example provided.
